#!/bin/bash
# Upload QuickUI catalog controls to http://quickui.org/release.

# Get location of parent folder relative to location of this script.
scriptPath=$(cd ${0%/*} && echo $PWD/${0##*/})
scriptFolder=`dirname "$scriptPath"`
projectFolder="$scriptFolder/.."

savePath=$(cd)

# FTP script wants to start out in project root
cd $projectFolder
psftp -b $scriptFolder/upload.ftp

cd $savePath
